# ---------- 1️⃣ Build stage ----------
FROM node:20-alpine AS builder

WORKDIR /roqart-fe

# Activar pnpm
RUN corepack enable && corepack prepare pnpm@latest --activate

# Copiar archivos de dependencias
COPY package.json pnpm-lock.yaml ./

# Instalar dependencias
RUN pnpm install --frozen-lockfile

# Copiar código
COPY . .

# Set next env vars
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_PUBLISHABLE_API_KEY
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_PUBLISHABLE_API_KEY=$NEXT_PUBLIC_PUBLISHABLE_API_KEY

# Build
RUN pnpm build

# ---------- 2️⃣ Production stage ----------
FROM node:20-alpine

WORKDIR /roqart-fe

RUN corepack enable && corepack prepare pnpm@latest --activate

# Copiar solo lo necesario
COPY --from=builder /roqart-fe/package.json ./
COPY --from=builder /roqart-fe/pnpm-lock.yaml ./
COPY --from=builder /roqart-fe/.next ./.next
COPY --from=builder /roqart-fe/public ./public
COPY --from=builder /roqart-fe/node_modules ./node_modules
COPY --from=builder /roqart-fe/next.config.ts ./

EXPOSE 3000

CMD ["pnpm", "start"]
